// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: bulk_insert.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulkInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InsertedCount int32                  `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkInsertResponse) Reset() {
	*x = BulkInsertResponse{}
	mi := &file_bulk_insert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsertResponse) ProtoMessage() {}

func (x *BulkInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bulk_insert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsertResponse.ProtoReflect.Descriptor instead.
func (*BulkInsertResponse) Descriptor() ([]byte, []int) {
	return file_bulk_insert_proto_rawDescGZIP(), []int{0}
}

func (x *BulkInsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkInsertResponse) GetInsertedCount() int32 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

var File_bulk_insert_proto protoreflect.FileDescriptor

const file_bulk_insert_proto_rawDesc = "" +
	"\n" +
	"\x11bulk_insert.proto\x12\x0eseirraromeo.v1\"U\n" +
	"\x12BulkInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\x05R\rinsertedCountB<Z:github.com/RomeoIndiaJulietUniform/thismightwork/api/pb;pbb\x06proto3"

var (
	file_bulk_insert_proto_rawDescOnce sync.Once
	file_bulk_insert_proto_rawDescData []byte
)

func file_bulk_insert_proto_rawDescGZIP() []byte {
	file_bulk_insert_proto_rawDescOnce.Do(func() {
		file_bulk_insert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bulk_insert_proto_rawDesc), len(file_bulk_insert_proto_rawDesc)))
	})
	return file_bulk_insert_proto_rawDescData
}

var file_bulk_insert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bulk_insert_proto_goTypes = []any{
	(*BulkInsertResponse)(nil), // 0: seirraromeo.v1.BulkInsertResponse
}
var file_bulk_insert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bulk_insert_proto_init() }
func file_bulk_insert_proto_init() {
	if File_bulk_insert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bulk_insert_proto_rawDesc), len(file_bulk_insert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bulk_insert_proto_goTypes,
		DependencyIndexes: file_bulk_insert_proto_depIdxs,
		MessageInfos:      file_bulk_insert_proto_msgTypes,
	}.Build()
	File_bulk_insert_proto = out.File
	file_bulk_insert_proto_goTypes = nil
	file_bulk_insert_proto_depIdxs = nil
}
