// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: seirraromeo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_seirraromeo_proto protoreflect.FileDescriptor

const file_seirraromeo_proto_rawDesc = "" +
	"\n" +
	"\x11seirraromeo.proto\x12\x0eseirraromeo.v1\x1a\finsert.proto\x1a\fupdate.proto\x1a\fdelete.proto\x1a\x11bulk_insert.proto\x1a\x10collection.proto2\xb6\x05\n" +
	"\vSeirraRomeo\x12I\n" +
	"\x06Insert\x12\x1d.seirraromeo.v1.InsertRequest\x1a\x1e.seirraromeo.v1.InsertResponse\"\x00\x12I\n" +
	"\x06Upsert\x12\x1d.seirraromeo.v1.InsertRequest\x1a\x1e.seirraromeo.v1.InsertResponse\"\x00\x12I\n" +
	"\x06Update\x12\x1d.seirraromeo.v1.UpdateRequest\x1a\x1e.seirraromeo.v1.UpdateResponse\"\x00\x12I\n" +
	"\x06Delete\x12\x1d.seirraromeo.v1.DeleteRequest\x1a\x1e.seirraromeo.v1.DeleteResponse\"\x00\x12S\n" +
	"\n" +
	"BulkInsert\x12\x1d.seirraromeo.v1.InsertRequest\x1a\".seirraromeo.v1.BulkInsertResponse\"\x00(\x01\x12a\n" +
	"\x10CreateCollection\x12'.seirraromeo.v1.CreateCollectionRequest\x1a\".seirraromeo.v1.CollectionResponse\"\x00\x12]\n" +
	"\x0eDropCollection\x12%.seirraromeo.v1.DropCollectionRequest\x1a\".seirraromeo.v1.CollectionResponse\"\x00\x12d\n" +
	"\x0fListCollections\x12&.seirraromeo.v1.ListCollectionsRequest\x1a'.seirraromeo.v1.ListCollectionsResponse\"\x00Bv\n" +
	"&io.seirraromeo.client.grpc.protocol.v1B\x10SeirraRomeoProtoZ:github.com/RomeoIndiaJulietUniform/thismightwork/api/pb;pbb\x06proto3"

var file_seirraromeo_proto_goTypes = []any{
	(*InsertRequest)(nil),           // 0: seirraromeo.v1.InsertRequest
	(*UpdateRequest)(nil),           // 1: seirraromeo.v1.UpdateRequest
	(*DeleteRequest)(nil),           // 2: seirraromeo.v1.DeleteRequest
	(*CreateCollectionRequest)(nil), // 3: seirraromeo.v1.CreateCollectionRequest
	(*DropCollectionRequest)(nil),   // 4: seirraromeo.v1.DropCollectionRequest
	(*ListCollectionsRequest)(nil),  // 5: seirraromeo.v1.ListCollectionsRequest
	(*InsertResponse)(nil),          // 6: seirraromeo.v1.InsertResponse
	(*UpdateResponse)(nil),          // 7: seirraromeo.v1.UpdateResponse
	(*DeleteResponse)(nil),          // 8: seirraromeo.v1.DeleteResponse
	(*BulkInsertResponse)(nil),      // 9: seirraromeo.v1.BulkInsertResponse
	(*CollectionResponse)(nil),      // 10: seirraromeo.v1.CollectionResponse
	(*ListCollectionsResponse)(nil), // 11: seirraromeo.v1.ListCollectionsResponse
}
var file_seirraromeo_proto_depIdxs = []int32{
	0,  // 0: seirraromeo.v1.SeirraRomeo.Insert:input_type -> seirraromeo.v1.InsertRequest
	0,  // 1: seirraromeo.v1.SeirraRomeo.Upsert:input_type -> seirraromeo.v1.InsertRequest
	1,  // 2: seirraromeo.v1.SeirraRomeo.Update:input_type -> seirraromeo.v1.UpdateRequest
	2,  // 3: seirraromeo.v1.SeirraRomeo.Delete:input_type -> seirraromeo.v1.DeleteRequest
	0,  // 4: seirraromeo.v1.SeirraRomeo.BulkInsert:input_type -> seirraromeo.v1.InsertRequest
	3,  // 5: seirraromeo.v1.SeirraRomeo.CreateCollection:input_type -> seirraromeo.v1.CreateCollectionRequest
	4,  // 6: seirraromeo.v1.SeirraRomeo.DropCollection:input_type -> seirraromeo.v1.DropCollectionRequest
	5,  // 7: seirraromeo.v1.SeirraRomeo.ListCollections:input_type -> seirraromeo.v1.ListCollectionsRequest
	6,  // 8: seirraromeo.v1.SeirraRomeo.Insert:output_type -> seirraromeo.v1.InsertResponse
	6,  // 9: seirraromeo.v1.SeirraRomeo.Upsert:output_type -> seirraromeo.v1.InsertResponse
	7,  // 10: seirraromeo.v1.SeirraRomeo.Update:output_type -> seirraromeo.v1.UpdateResponse
	8,  // 11: seirraromeo.v1.SeirraRomeo.Delete:output_type -> seirraromeo.v1.DeleteResponse
	9,  // 12: seirraromeo.v1.SeirraRomeo.BulkInsert:output_type -> seirraromeo.v1.BulkInsertResponse
	10, // 13: seirraromeo.v1.SeirraRomeo.CreateCollection:output_type -> seirraromeo.v1.CollectionResponse
	10, // 14: seirraromeo.v1.SeirraRomeo.DropCollection:output_type -> seirraromeo.v1.CollectionResponse
	11, // 15: seirraromeo.v1.SeirraRomeo.ListCollections:output_type -> seirraromeo.v1.ListCollectionsResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_seirraromeo_proto_init() }
func file_seirraromeo_proto_init() {
	if File_seirraromeo_proto != nil {
		return
	}
	file_insert_proto_init()
	file_update_proto_init()
	file_delete_proto_init()
	file_bulk_insert_proto_init()
	file_collection_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seirraromeo_proto_rawDesc), len(file_seirraromeo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seirraromeo_proto_goTypes,
		DependencyIndexes: file_seirraromeo_proto_depIdxs,
	}.Build()
	File_seirraromeo_proto = out.File
	file_seirraromeo_proto_goTypes = nil
	file_seirraromeo_proto_depIdxs = nil
}
